name = "server-sg"
main = "_worker.js"
compatibility_date = "2025-12-28"
[[routes]]
pattern = "okepeb.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.okepeb.web.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.okepeb.web.id"
custom_domain = true
[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "0141076a-c859-408d-8dd4-2f0f8a3413f0"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
